psychic/psychic/urls.py
from django.contrib import admin
from django.urls import path, include

handler400 = 'quiz.views.handler400'
handler403 = 'quiz.views.handler403'
handler404 = 'quiz.views.handler404'
handler500 = 'quiz.views.handler500'

urlpatterns = [
    path('', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

psychic/quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.quiz, name='quiz'),
    path('<int:quiz_id>/submit', views.submit, name='submit'),
]

psychic/quiz/models.py
import datetime

from django.db import models
from django.utils import timezone


class Quiz(models.Model):
    title = models.CharField(max_length=200)
    description_text = models.TextField()
    submit_text = models.TextField(default='Your response was recorded. Thank you!')
    pub_date = models.DateTimeField('publish_date', default=timezone.now)
    exp_date = models.DateTimeField('expire_date', default=timezone.now()+datetime.timedelta(days=365))

    def __str__(self):
        return self.title

    def is_active(self, time_to_check=timezone.now()):
        return time_to_check >= self.pub_date and time_to_check <= self.exp_date
    is_active.boolean = True

    def is_valid(self):
        if not self.question_set.all():
            return False
        for question in self.question_set.all():
            if not question.is_valid():
                return False
        return True
    is_valid.boolean = True


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text

    def is_valid(self):
        """
        Criteria for a valid question: must have 2+ choices, must have only valid choices
        """
        if not self.choice_set.all() or len(self.choice_set.all()) < 2:
            return False
        for choice in self.choice_set.all():
            if not choice.is_valid():
                return False
        return True


class Prediction(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    prediction_title = models.CharField(max_length=200)

    def __str__(self):
        return self.prediction_title


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    prediction = models.ForeignKey(Prediction, on_delete=models.SET_NULL, null=True, related_name='prediction1')
    prediction2 = models.ForeignKey(Prediction, on_delete=models.SET_NULL, null=True, blank=True, related_name='prediction2')
    prediction3 = models.ForeignKey(Prediction, on_delete=models.SET_NULL, null=True, blank=True, related_name='prediction3')
    prediction4 = models.ForeignKey(Prediction, on_delete=models.SET_NULL, null=True, blank=True, related_name='prediction4')
    prediction5 = models.ForeignKey(Prediction, on_delete=models.SET_NULL, null=True, blank=True, related_name='prediction5')
    weight = models.FloatField()

    def __str__(self):
        return self.choice_text

    def is_valid(self):
        """
        Criteria for a valid choice: prediction and question must be of the same quiz
        """
        if self.prediction.quiz.pk != self.question.quiz.pk:
            return False
        return True

class Submission(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    client_name = models.CharField(max_length=200)
    client_email = models.CharField(max_length=200)
    time_submitted = models.DateTimeField('time_submitted')
    calculated_prediction = models.ForeignKey(Prediction, on_delete=models.SET_NULL, null=True)
    choices = models.ManyToManyField(Choice)

    def __str__(self):
        return self.client_name.replace(" ", "")

psychic/quiz/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse, Http404, HttpResponseBadRequest
from django.utils import timezone

from .models import Quiz, Question, Choice, Prediction, Submission
from . import settings

import os
import pathlib


class IndexView(generic.ListView):
    template_name = 'quiz/index.html'
    context_object_name = 'quiz_list'

    def get_queryset(self):
        """
        Return all valid quizzes
        """
        return [quiz for quiz in Quiz.objects.all() if quiz.is_active() and quiz.is_valid()]


class QuizView(generic.DetailView):
    context_object_name = 'quiz'
    template_name = 'quiz/quiz.html'
    model = Quiz


def quiz(request, pk):
    selected_quiz = get_object_or_404(Quiz, pk=pk)
    if (selected_quiz.is_valid() and selected_quiz.is_active()) or settings.DEBUG:
        context = {
            'quiz': selected_quiz,
        }
        return render(request, 'quiz/quiz.html', context)
    else:
        return render(request, 'quiz/invalid.html')


def submit(request, quiz_id, question_format="question{}", save_path=settings.LOG_DIR):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    quiz_results = {}

    time_submitted = timezone.now()
    quiz_results['time_submitted'] = time_submitted.isoformat()

    if 'name' in request.POST.keys() and request.POST['name']:
        quiz_results['name'] = request.POST['name']
    else:
        return HttpResponseBadRequest("No name provided!")

    if 'email' in request.POST.keys() and request.POST['email']:
        quiz_results['email'] = request.POST['email']
    else:
        return HttpResponseBadRequest("No email provided!")

    # Set up prediction set to sum relevant weights
    prediction_set = {}

    for prediction in quiz.prediction_set.all():
        prediction_set[prediction.pk] = 0

    # Set up selected choices set
    quiz_results['choices'] = {}

    for question in quiz.question_set.all():
        if not question_format.format(question.id) in request.POST.keys():
            return HttpResponseBadRequest("Please answer all of the questions")
        else:
            selected_choice = get_object_or_404(Choice, pk=request.POST[question_format.format(question.id)])
            selected_predictions = [i for i in [selected_choice.prediction, selected_choice.prediction2, selected_choice.prediction3, selected_choice.prediction4, selected_choice.prediction5] if i is not None]
            for prediction in selected_predictions:
                prediction_set[prediction.pk] += selected_choice.weight
            quiz_results['choices'][question.pk] = selected_choice.pk

    quiz_results['prediction_set'] = prediction_set

    final_prediction_pk = max(prediction_set.keys(), key=(lambda k: prediction_set[k]))
    final_prediction = Prediction.objects.get(pk=final_prediction_pk)

    quiz_results['prediction'] = final_prediction.prediction_title

    # Collect client data
    quiz_results['client_data'] = _get_client_data(request)

    # Write submission to database
    submission = Submission(quiz=quiz, client_name=quiz_results['name'],
                            client_email=quiz_results['email'], time_submitted=time_submitted,
                            calculated_prediction=final_prediction)
    submission.save()

    for choice_pk in quiz_results['choices'].values():
        submission.choices.add(Choice.objects.get(pk=choice_pk))

    return submit_response(request, quiz)


def submit_response(request, quiz):
    context = {
        'quiz': quiz,
    }
    return render(request, 'quiz/submit.html', context)


def _get_client_data(request):
    # Collect client data
    client_data = {
        'server_name': request.META['SERVER_NAME'],
        'server_port': request.META['SERVER_PORT'],
        'http_host': request.META['HTTP_HOST'],
        'http_user_agent': request.META['HTTP_USER_AGENT'],
        'clinet_ip': request.META['REMOTE_ADDR'],
    }

    return client_data

psychic/quiz/templates/quiz/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <title>{% block title %}{% endblock %}</title>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>

        <link rel="icon" type="image/png" href="{% static 'quiz/img/favicon.png' %}">
        
        <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}">
        <link type="text/css" rel="stylesheet" href="{% static 'quiz/css/quiz.css' %}">
        {% block css %}{% endblock %}
    </head>

    <body>
        <header>
            <nav class="blue darken-3" role="navigation">
                <div class="container">
                    <div class="nav-wrapper">
                        <a id="logo-container" href="{% url 'quiz:index' %}" class="brand-logo hide-on-med-and-down">Psychic</a>
                        <ul class="right hide-on-med-and-down">
                            <li><a class="waves-effect waves-light" href="{% url 'quiz:index' %}">Home</a></li>
                        </ul>

                        <ul id="nav-mobile" class="sidenav">
                            <!--<li class="logo center"><a id="logo-container" href="{% url 'quiz:index' %}" class="brand-logo">
                                <img id="front-page-logo" type="image/png" src="{% static 'quiz/img/favicon.png' %}">
                            </a></li>-->
                            <li class="logo center">
                                <a href="{% url 'quiz:index' %}" id="logo-container">
                                    <img src="{% static 'quiz/img/favicon.png' %}" id="front-page-logo">
                                </a>
                            </li>
                            <div class="divider"></div>
                            <li><a href="{% url 'quiz:index' %}">Home</a></li>
                        </ul>
                        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    </div>
                </div>
            </nav>
        </header>

        <main>
            {% block main %}{% endblock %}
        </main>

        <footer class="grey darken-3 page-footer">
            <div class="container">
                <div class="row">
                    <div class="col m6 s12">
                        <h5 class="text-primary-color">Psychic</h5>
                        <p class="text-primary-color">{% lorem b %}</p>
                    </div>
                    <div class="col m3 s12 offset-m1">
                        <h5 class="text-primary-color">Pages</h5>
                        <ul>
                            <li><a class="grey-text text-lighten-2" href="{% url 'quiz:index' %}">Home</a></li>
                            {% for i in i|rjust:3 %}
                            <li><a class="grey-text text-lighten-2" href="{% url 'quiz:index' %}">{% lorem 2 w random %}</a></li>
                            {% endfor %}
                    </div>
                </div>
            </div>

            <div class="footer-copyright">
                <div class="container">
                    &copy; Wesley Soo-Hoo 2019 | made with <a class="grey-text text-lighten-2" href="materializecss.com" target="_blank">MaterializeCSS</a>
                    <a class="grey-text text-lighten-2 right modal-trigger" href="#license">MIT License</a>
                </div>
            </div>

            <div id="license" class="modal bottom-sheet">
                <div class="modal-content primary-text-color container">
                    <h4>The MIT License (MIT)</h4>
                    <p> Copyright &copy; 2019 Wesley Soo-Hoo <br><br>
                    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.<br><br>
                    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</p><br>
                </div>
            </div> 
        </footer>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="{% static 'js/materialize.js' %}"></script>
        <script src="{% static 'quiz/js/init.js' %}"></script>
    </body>
</html>

psychic/quiz/templates/quiz/header.html
{% block header %}
<nav class="blue" role="navigation">
    <div class="container">
        <div class="nav-wrapper">
            <a id="logo-container" href="/" class="brand-logo hide-on-med-and-down">Test</a>
            <ul class="right hide-on-med-and-down">
                <li><a class="waves-effect waves-light" href="/">Home</a></li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

psychic/quiz/templates/quiz/index.html
{% extends "quiz/base.html" %} 
{% include "quiz/header.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block main %}
    <div class="container center">
        <h1>Psychic</h1>
        <h5 class="light">Subtitle</h5>
    </div>
    <div class="container">
        <br>
        {% if quiz_list %}
        <div class="row">
        {% for quiz in quiz_list %}
            <div class="col s12 m4">
                <div class="card grey darken-1">
                    <div class="card-content white-text">
                        <span class="card-title">{{ quiz.title }}</span>
                        <p>{{ quiz.description_text }}</p>
                    </div>
                    <div class="card-action">
                        <a class="white-text" href="{% url 'quiz:quiz' quiz.id %}">Go</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %}

psychic/quiz/templates/quiz/invalid.html
{% extends "quiz/base.html" %} 
{% include "quiz/header.html" %}
{% load static %}

{% block title %}404 Error{% endblock %}

{% block main %}
    <div class="container center">
        <h5 class="light">Quiz not found!<h5>

        <a href="{% url 'quiz:index' %}" class="return"><img src="{% static 'quiz/img/boba.gif' %}"></a>
    </div>
{% endblock %}

psychic/quiz/templates/quiz/quiz.html
{% extends 'quiz/base.html' %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block main %}
<div class="container">
    {% if quiz and quiz.question_set.all %}
    <h1 class="light center">{{ quiz.title }}</h1>
    <form action="{% url 'quiz:submit' quiz.id %}" method="post" class="col s12">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col m6 s12">
                <i class="material-icons prefix">account_circle</i>
                <input type="text" name="name" id="name" class="validate" required>
                <label for="name">Name</label>
            </div>

            <div class="input-field col m6 s12">
                <i class="material-icons prefix">email</i>
                <input type="email" name="email" id="email" class="validate" required>
                <label for="email">Email address</label>
            </div>
        </div>

        {% for question in quiz.question_set.all %}
            {% if question.choice_set.all %}
                <!-- Question {{ question.id }} -->
                <b>{{ question.question_text }}</b><br>
                {% for choice in question.choice_set.all %}
                    <p>
                        <label>
                            <input type="radio" name="question{{ question.id }}" id="choice{{ choice.id }}" value="{{ choice.id }}" required>
                            <span class="grey-text text-darken-3">{{ choice.choice_text }}</span>
                        </label>
                    </p>
                {% endfor %}
            {% endif %}
        {% endfor %}
        <button class="blue darken-3 btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>
    {% else %}
        No quiz
    {% endif %}
</div>
{% endblock %}

psychic/quiz/templates/quiz/submit.html
{% extends "quiz/base.html" %} 
{% include "quiz/header.html" %}
{% load static %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block main %}
    <div class="container center">
        <h5 class="light">{{ quiz.submit_text }}</h5>

        <a href="{% url 'quiz:index' %}" class="return"><img src="{% static 'quiz/img/boba.gif' %}"></a>
    </div>
{% endblock %}